### ISSUE TITLE
Unsubscribe method does not remove Subscription from Client.

### ISSUE THREAD

**Issue by hound672** [centrifugal/centrifuge-go#41]
Hello.

Example:
Create subscription:
`subscription, err := client.NewSubscription(channelName)`
`// check error`
`err = subscription.Subscribe()`
`// check error`

Later when I'd like to unsubscribe
`
err = subscription.Unsubscribe()
// check error
`

But my `client` object still has `subscription` object in `subs map[string]*Subscription`

**Comment by FZambia** [comment]
@hound672 hello. This is expected, do you have any specific problem due to this behavior?

Actually, a similar topic already araised in other Centrifuge clients – some clients have methods to free Subscription from a map, Javascript client does this automatically on Unsubscribe. We can do it here too.

**Comment by FZambia** [comment]
Yep, thanks, I suppose automatic removing on Unsubscribe is the preferred way.

**Comment by hound672** [comment]
https://github.com/centrifugal/centrifuge-go/pull/42
please check

**Comment by FZambia** [comment]
@hound672 will add some comments, changelog, etc and release very soon.

**Comment by hound672** [comment]
Thanks!
