### ISSUE TITLE
Panic due to invalid endpoint

### ISSUE THREAD

**Issue by Lachann** [centrifugal/centrifuge-go#83]
Currently, if the provided endpoint fails to parse when making a new client, the lib panics:
https://github.com/centrifugal/centrifuge-go/blob/master/client.go#L101-L112

In our case the endpoint is provided by another microservice at runtime, and there's no 100% guarantee it'll be valid, so to safeguard against crashing we have to `recover` and check the panic.

Would it be possible to make it return an error instead of panicking, or at least have a way to validate the endpoint beforehand?

**Comment by FZambia** [comment]
@Lachann hello, as I pointed in #84 you can check the endpoint in your app code before initializing Client. I also suggest validating such endpoints and restrict domains they can contain due to security considerations.

From centrifuge-go side – I suppose we must better document the current behavior.

**Comment by FZambia** [comment]
Addressed in fadc754b17f841662c4641cfaed6fb8cd58ca27b
